services:
  db:
    image: postgres:16
    container_name: anime_db
    environment:
      POSTGRES_USER: anime_user
      POSTGRES_PASSWORD: anime_pass
      POSTGRES_DB: anime_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build:
      context: ./backend
    #image: navisper/anime-backend:1.0
    container_name: anime_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://anime_user:anime_pass@db:5432/anime_db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    #image: navisper/anime-frontend:1.0
    container_name: anime_frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db_data:
